"""
Introduction to Machine Learning

Lab 1: Polynomial regression

TODO: Add your information here.
    IMPORTANT: Please ensure this script
    (1) Run script_lab2.py on Python >=3.6;
    (2) No errors;
    (3) Finish in tolerable time on a single CPU (e.g., <=10 mins);
    (4) All your need is numpy and matplotlib, so do not import anything else.
    (5) For the functions you implemented, do not change the random seed (r_seed)
Student name(s):Songchen Wang
Student ID(s):2024201594
"""

import numpy as np
import matplotlib.pyplot as plt

# don't add any other packages


# data simulator and testing function (Don't change them)
def polynomial_data_simulator(
    n_train: int = 200,
    n_test: int = 10,
    order: int = 5,
    v_noise: float = 0.5,
    r_seed: int = 42,
) -> dict:
    """
    Simulate the training and testing data generated by a polynomial model
    :param n_train: the number of training data
    :param n_test: the number of testing data
    :param order: the order of the polynomial function
    :param v_noise: the variance of noise
    :param r_seed: the random seed
    :return:
        a dictionary containing training set, testing set, and the ground truth parameters
    """
    x_train = 4 * (np.random.RandomState(r_seed).rand(n_train) - 0.5)
    X_train = np.array([x_train**d for d in range(order)]).T
    x_test = 5 * (np.random.RandomState(r_seed).rand(n_test) - 0.5)
    X_test = np.array([x_test**d for d in range(order)]).T
    weights = np.random.RandomState(r_seed).randn(order, 1)
    y_train = X_train @ weights + v_noise * np.random.RandomState(r_seed).randn(
        n_train, 1
    )
    y_test = X_test @ weights + v_noise * np.random.RandomState(r_seed).randn(n_test, 1)
    data = {"train": [x_train, y_train], "test": [x_test, y_test], "real": weights}
    return data


def visualization_curves(weights: np.ndarray, label: str, curve_type: str):
    landmarks = 5 * (np.arange(0, 100) / 100 - 0.5)
    order = weights.shape[0]
    curve = np.array([landmarks**d for d in range(order)]).T @ weights
    plt.plot(landmarks, curve, curve_type, label=label)


def visualization_points(x: np.ndarray, y: np.ndarray, label: str, point_type: str):
    plt.plot(x, y, point_type, label=label)


def testing(x: np.ndarray, y: np.ndarray, weights: np.ndarray) -> float:
    """
    Compute the MSE of regression based on current model
    :param x: testing data with size (N, )
    :param y: testing label with size (N, 1)
    :param weights: model parameter with size (D, 1)
    :return:
        MSE
    """
    order = weights.shape[0]
    x_test = np.array([x**d for d in range(order)]).T
    y_est = x_test @ weights
    return np.sum((y - y_est) ** 2) / x.shape[0]


# Task 1: Implement the training function of a polynomial regression model,
# which derives the closed form solution directly
def training(x: np.ndarray, y: np.ndarray, order: int) -> np.ndarray:
    """
    The training function of polynomial regression model
    :param x: input data with size (N,)
    :param y: labels of data with size (N, 1)
    :param order: the hyper-parameter determining the order of the polynomial function
    :return:
        a weight vector with size (D, 1), D is the order of polynomial function.
    """
    # TODO: Change the code below and implement the closed-form solution of polynomial regression
    x1 = np.array([x**d for d in range(order)]).T
    w = np.linalg.inv(x1.T @ x1) @ x1.T @ y
    return w


# Task 2: Implement the training function of a polynomial regression model,
# which implements the stochastic gradient descent (sgd) algorithm.
def training_sgd(
    x: np.ndarray,
    y: np.ndarray,
    order: int,
    epoch: int = 10,
    batch_size: int = 10,
    lr: float = 1e-4,
    r_seed: int = 42,
) -> np.ndarray:
    """
    The stochastic gradient descent method
    :param x: input data with size (N,)
    :param y: labels of data with size (N, 1)
    :param order: the hyper-parameter determining the order of the polynomial function
    :param epoch: the number of epochs
    :param batch_size: the batch size for sgd
    :param lr: the learning rate
    :param r_seed: random seed
    :return:
        a weight vector with size (D, 1)
    """
    # TODO: Change the code below and implement the SGD algorithm of polynomial regression
    w = np.random.RandomState(r_seed).randn(order, 1)
    n_size = x.shape[0]
    r = np.random.RandomState(r_seed)
    for i in range(epoch):
        indices = r.permutation(n_size)
        x_change = x[indices]
        y_change = y[indices]
        for j in range(0, n_size, batch_size):
            x_batch = x_change[j : j + batch_size]
            y_batch = y_change[j : j + batch_size]
            a_size = x_batch.shape[0]
            x1 = np.array([x_batch**d for d in range(order)]).T
            y_est = x1 @ w
            grad = -2 * x1.T @ (y_batch - y_est) / a_size
            w -= lr * grad
    return w


# Task 3: Implement various data normalization method.
def data_normalization(x: np.ndarray, order: int, method: str = "L2") -> tuple:
    """
    implement various data_normalization method
    :param x: input data with size (N, )
    :param order: the hyper-parameter determining the order of the polynomial function
    :param method: 'L2': ensure the L2-norm of each column of data matrix is 1
                   'L1': ensure the L1-norm of each column of data matrix is 1
                   'Max': ensure the Infinity-norm of each column of data matrix is 1
    :return:
        A data matrix with size (N, D), each column is normalized according to the method we set
        A scaling vector containing the norms of original columns, with size (D, )
    """
    # TODO: Implement different normalization methods below.
    #  The output should include normalized data and the scaling vector
    X = np.array([x**d for d in range(order)]).T
    if method == "L2":
        scales = np.linalg.norm(X, ord=2, axis=0)
    elif method == "L1":
        scales = np.linalg.norm(X, ord=1, axis=0)
    elif method == "Max":
        scales = np.linalg.norm(X, ord=np.inf, axis=0)
    else:
        raise ValueError("未指定: {}".format(method))
    scales[scales == 0] = 1.0
    X_normalized = X / scales
    return X_normalized, scales


# Task 4 and 5: Train and test models based on normalized data. The training method is SGD
def training_sgd_normalized(
    x: np.ndarray,
    y: np.ndarray,
    order: int,
    epoch: int = 10,
    batch_size: int = 10,
    lr: float = 1e-4,
    method: str = "L2",
    r_seed: int = 42,
) -> tuple:
    """
    The stochastic gradient descent method
    :param x: input data with size (N,)
    :param y: labels of data with size (N, 1)
    :param order: the hyper-parameter determining the order of the polynomial function
    :param epoch: the number of epochs
    :param batch_size: the batch size for sgd
    :param lr: the learning rate
    :param method: the data normalization method (L2, L1, or Max)
    :param r_seed: random seed
    :return:
        w1: A weight vector with size (D, 1)
        a: A scaling vector containing the norms of original columns, with size (D, )
        w2: A weight vector corresponding to the model trained on the original data (derived based on w1 directly)
    """
    # TODO: Implement the SGD algorithm based on normalized data.
    #  (Hint: A simple combination of the SGD and the normalization function you implemented above)
    X_normalized, scales = data_normalization(x, order, method)
    w1 = np.random.RandomState(r_seed).randn(order, 1)
    n_size = X_normalized.shape[0]
    r = np.random.RandomState(r_seed)
    for i in range(epoch):
        indices = r.permutation(n_size)
        X_change = X_normalized[indices]
        y_change = y[indices]
        for j in range(0, n_size, batch_size):
            x_batch = X_change[j : j + batch_size]
            y_batch = y_change[j : j + batch_size]
            a_size = x_batch.shape[0]
            y_est = x_batch @ w1
            grad = -2 * x_batch.T @ (y_batch - y_est) / a_size
            w1 -= lr * grad
    w2 = w1 / scales[:, np.newaxis]
    return w1, scales, w2


def testing_normalized(
    x: np.ndarray, y: np.ndarray, weights: np.ndarray, scaling: np.ndarray
) -> float:
    """
    Compute the MSE of regression based on current model
    :param x: testing data with size (N, )
    :param y: testing label with size (N, 1)
    :param weights: model parameter with size (D, 1)
    :param scaling: A scaling vector containing the norms of original columns, with size (D, )
    :return:
        MSE
    """
    # TODO: Implement the testing function based on the normalized data
    #  (Hint 1: Please refer to the "testing" function shown above.
    #  (Hint 2: Think about why we need to take "scaling" as an input and where it is from.)
    y1 = testing(x, y, weights / scaling[:, np.newaxis])
    return y1


# Testing script
if __name__ == "__main__":
    data = polynomial_data_simulator()
    orders = [3, 5, 7, 9]
    for i in range(len(orders)):
        w_est1 = training(x=data["train"][0], y=data["train"][1], order=orders[i])
        w_est2 = training_sgd(x=data["train"][0], y=data["train"][1], order=orders[i])
        w_est3, scales, w_est4 = training_sgd_normalized(
            x=data["train"][0], y=data["train"][1], order=orders[i]
        )
        difference = np.sum(np.abs(w_est1 - w_est4))
        print("Difference={:.4f}".format(difference))
        mse1 = testing(x=data["test"][0], y=data["test"][1], weights=w_est1)
        mse2 = testing(x=data["test"][0], y=data["test"][1], weights=w_est2)
        mse3 = testing_normalized(
            x=data["test"][0], y=data["test"][1], weights=w_est3, scaling=scales
        )
        print(
            "Order={}, mse1={:.4f}, mse2={:.4f}, mse3={:.4f}".format(
                orders[i], mse1, mse2, mse3
            )
        )
        plt.figure()
        visualization_points(
            x=data["train"][0],
            y=data["train"][1][:, 0],
            point_type="bx",
            label="training data",
        )
        visualization_points(
            x=data["test"][0],
            y=data["test"][1][:, 0],
            point_type="kx",
            label="testing data",
        )
        visualization_curves(
            weights=data["real"], label="ground truth", curve_type="r-"
        )
        visualization_curves(weights=w_est2, label="SGD estimator", curve_type="g--")
        plt.legend()
        plt.savefig("Order{}.png".format(orders[i]))
        plt.close("all")
