"""
Introduction to Machine Learning

Lab 3: Regularized linear regression

TODO: Add your information here.
    IMPORTANT: Please ensure this script
    (1) Run script_lab3.py on Python >=3.6;
    (2) No errors;
    (3) Do not add any additional libs or packages
    (4) Finish in tolerable time on a single CPU (e.g., <=10 mins);

Student name(s):
Student ID(s):
"""

import numpy as np

# don't add any other packages


# data simulator and testing function (Don't change them)
def linear_data_simulator(
    n_train: int = 50,
    n_test: int = 10,
    dim: int = 10,
    v_noise: float = 2,
    prior: str = "Gauss",
    noise: str = "Gauss",
    r_seed: int = 42,
) -> dict:
    """
    Simulate the training and testing data generated by a polynomial model
    :param n_train: the number of training data
    :param n_test: the number of testing data
    :param dim: the dimension of feature
    :param v_noise: the hyper-parameter controlling the variance of data noise
    :param prior: the prior distribution of model parameters, Gauss or Laplace
    :param noise: the noise type, Gauss or Laplace
    :param r_seed: the random seed
    :return:
        a dictionary containing training set, testing set, and the ground truth parameters
    """
    x_train = np.random.RandomState(r_seed).rand(n_train, dim)
    x_test = np.random.RandomState(r_seed).rand(n_test, dim)
    if prior == "Gauss":
        weights = np.random.RandomState(r_seed).randn(dim, 1)
    else:
        weights = np.random.RandomState(r_seed).laplace(loc=0, scale=1, size=(dim, 1))
    if noise == "Gauss":
        y_train = x_train @ weights + v_noise * np.random.RandomState(r_seed).randn(
            n_train, 1
        )
        y_test = x_test @ weights + v_noise * np.random.RandomState(r_seed).randn(
            n_test, 1
        )
    else:
        y_train = x_train @ weights + np.random.RandomState(r_seed).laplace(
            loc=0, scale=v_noise, size=(n_train, 1)
        )
        y_test = x_test @ weights + np.random.RandomState(r_seed).laplace(
            loc=0, scale=v_noise, size=(n_test, 1)
        )
    data = {"train": [x_train, y_train], "test": [x_test, y_test], "real": weights}
    return data


def mse(x: np.ndarray, x_est: np.ndarray) -> float:
    return np.sum((x - x_est) ** 2) / x.shape[0]


def testing(x: np.ndarray, y: np.ndarray, weights: np.ndarray) -> float:
    """
    Compute the MSE of regression based on current model
    :param x: testing data with size (N, )
    :param y: testing label with size (N, 1)
    :param weights: model parameter with size (D, 1)
    :return:
        MSE
    """
    y_est = x @ weights
    return mse(y, y_est)


# Task 1: Implement the OMP algorithm for sparse coding
# which derives the closed form solution directly
def omp(x: np.ndarray, y: np.ndarray, non_zeros: int = 2) -> np.ndarray:
    """
    The OMP algorithm for sparse coding

    min_w ||y - Xw||_2^2, s.t. ||w||_0=2

    :param x: input data with size (N, dim)
    :param y: labels of data with size (N, 1)
    :param non_zeros: the number of nonzero parameters
    :return:
        a weight vector with size (dim, 1)
    """
    # TODO: Change the code below and implement your learning method accordingly
    n, dim = x.shape
    w = np.zeros((dim, 1))
    r = y.copy()
    support = []
    col_norm2 = np.sum(x * x, axis=0)  # (dim,)

    for _ in range(non_zeros):
        corr = (x.T @ r).reshape(-1)  # (dim,)
        r_norm2 = (r.T @ r).item()
        eps = np.full(dim, np.inf, dtype=float)

        valid = col_norm2 > 0
        eps[valid] = r_norm2 - (corr[valid] ** 2) / col_norm2[valid]
        if support:
            eps[np.array(support, dtype=int)] = np.inf

        d = int(np.argmin(eps))
        if not np.isfinite(eps[d]):
            break
        support.append(d)

        xs = x[:, support]  # (n, k)
        theta_s = np.linalg.pinv(xs) @ y  # (k, 1)
        r = y - xs @ theta_s

    if support:
        w[np.array(support, dtype=int), :] = theta_s
    return w


# Task 2: Implement the training function of the ridge regression model,
# which implements the stochastic gradient descent (sgd) algorithm.
def training_sgd(
    x: np.ndarray,
    y: np.ndarray,
    gamma: float,
    epoch: int = 100,
    batch_size: int = 10,
    lr: float = 0.01,
    r_seed: int = 1,
) -> np.ndarray:
    """
    The stochastic gradient descent method of ridge regression.
    :param x: input data with size (N, dim)
    :param y: labels of data with size (N, 1)
    :param gamma: the weight of ridge regularizer
    :param epoch: the number of epochs
    :param batch_size: the batch size for sgd
    :param lr: the learning rate
    :param r_seed: random seed
    :return:
        a weight vector with size (order, 1)
    """
    num = x.shape[0]
    dim = x.shape[1]
    rng = np.random.RandomState(r_seed)
    w = rng.randn(
        dim, 1
    )  # 为了后面SGD的代码更简洁，在保持w初始化不变的情况下进行了小改动，之后的Task也有同样的处理
    # TODO: Add your code below
    bsz = min(batch_size, num)
    for _ in range(epoch):
        # 打乱数据顺序
        perm = rng.permutation(num)
        for start in range(0, num, bsz):
            idx = perm[start : start + bsz]
            x_batch = x[idx]
            y_batch = y[idx]
            # 计算梯度并更新参数
            grad = (-2.0 / x_batch.shape[0]) * (
                x_batch.T @ (y_batch - x_batch @ w)
            ) + 2.0 * gamma * w
            w -= lr * grad

    return w


# Task 3: Implement the training function of lasso regression
def soft_thresholding(x: np.ndarray, thres: float) -> np.ndarray:
    """
    The soft-thresholding operator
    :param x: input array with arbitrary size
    :param thres: the threshold
    :return:
        sign(x) * max{0, |x|-thres}
    """
    # TODO: Change the code below and implement your soft-thresholding method
    return np.sign(x) * np.maximum(np.abs(x) - thres, 0.0)


def training_lasso(
    x: np.ndarray, y: np.ndarray, gamma: float, iteration: int = 100, r_seed: int = 1
) -> np.ndarray:
    """
    The training function of lasso regression model

    min_w ||y - Xw||_2^2 + gamma * ||w||_1

    :param x: input data with size (N, dim)
    :param y: labels of data with size (N, 1)
    :param gamma: the weight of the lasso regularizer
    :param iteration: the number of iterations for soft-thresholding
    :param r_seed: the random seed for initializing model.
    :return:
        a weight vector with size (dim, 1)
    """
    dim = x.shape[1]
    rng = np.random.RandomState(r_seed)
    w = rng.randn(dim, 1)

    # TODO: Add your code below
    thres = 0.5 * gamma

    n = x.shape[0]
    col_norm2 = np.sum(x * x, axis=0)  # (dim,)
    r = y - x @ w  # 残差，初始为y - x @ w

    for _ in range(iteration):
        for d in range(dim):
            norm2 = float(col_norm2[d])
            x_d = x[:, d : d + 1]

            if norm2 <= 0.0:
                if w[d, 0] != 0.0:
                    r += x_d * w[d, 0]
                    w[d, 0] = 0.0
                continue

            rho = (x_d.T @ (r + x_d * w[d, 0])).item()

            new_wd = float(soft_thresholding(rho, thres) / norm2)
            delta = new_wd - float(w[d, 0])
            if delta != 0.0:
                w[d, 0] = new_wd
                r -= x_d * delta

    return w


# Task 4: Implement the training function of the linear regression with elastic net regression
def training_elastic(
    x: np.ndarray,
    y: np.ndarray,
    gamma1: float,
    gamma2: float,
    iteration: int = 100,
    r_seed: int = 1,
) -> np.ndarray:
    """
    The training function of lasso regression model

    min_w ||y - Xw||_2^2 + gamma1 * ||w||_1 + gamma2 * ||w||_2^2

    :param x: input data with size (N, dim)
    :param y: labels of data with size (N, 1)
    :param gamma1: the weight of the lasso regularizer
    :param gamma2: the weight of the ridge regularizer
    :param iteration: the number of iterations for soft-thresholding
    :param r_seed: the random seed for initializing model.
    :return:
        a weight vector with size (dim, 1)
    """
    # TODO: Change the code below and implement your learning method accordingly
    dim = x.shape[1]
    rng = np.random.RandomState(r_seed)
    w = rng.randn(dim, 1)

    thres = 0.5 * gamma1
    col_norm2 = np.sum(x * x, axis=0)  # (dim,)

    r = y - x @ w

    for _ in range(iteration):
        for d in range(dim):
            x_d = x[:, d : d + 1]  # 第 d 列
            norm2 = float(col_norm2[d])  # ||x_d||^2

            if norm2 <= 0.0:
                if w[d, 0] != 0.0:
                    # 把旧的贡献加回残差，再把 w_d 置 0
                    r += x_d * w[d, 0]
                    w[d, 0] = 0.0
                continue

            # 利用当前残差 r = y - Xw：
            rho = (x_d.T @ (r + x_d * w[d, 0])).item()

            # Elastic Net 的分母会多一个 gamma2
            denom = norm2 + gamma2
            new_wd = float(soft_thresholding(rho, thres) / denom)

            # 用增量方式更新残差：r_new = y - X w_new = r_old - x_d * (new_wd - old_wd)
            delta = new_wd - float(w[d, 0])
            if delta != 0.0:
                w[d, 0] = new_wd
                r -= x_d * delta

    return w


# Task 5: Implement the iteratively reweighted least square (IRLS) to solve min_w ||y - Xw||_1
def training_irls(
    x: np.ndarray, y: np.ndarray, iteration: int = 100, r_seed: int = 1
) -> np.ndarray:
    """
    min_w ||y - Xw||_1 (MAE minimization)

    :param x: testing data with size (N, dim)
    :param y: testing label with size (N, 1)
    :param iteration: the number of iterations for soft-thresholding
    :param r_seed: the random seed for initializing model.
    :return:
        a weight vector with size (dim, 1)
    """
    dim = x.shape[1]
    w = np.random.RandomState(r_seed).randn(dim, 1)
    # TODO: Add your code below
    eps = 1e-8

    for _ in range(iteration):
        r = y - x @ w  # (N,1)
        alpha = 1.0 / (np.abs(r) + eps)  # (N,1)

        # 利用广播实现 A@X 和 A@y：
        ax = x * alpha  # (N,D) 等价于 A X
        ay = y * alpha  # (N,1) 等价于 A y

        # 计算正规方程：(X^T A X) w = X^T A y
        xtax = x.T @ ax  # (D,D)
        xtay = x.T @ ay  # (D,1)

        # 解线性方程得到新的 w。若遇到数值奇异，用伪逆兜底。
        try:
            w = np.linalg.solve(xtax, xtay)
        except np.linalg.LinAlgError:
            w = np.linalg.pinv(xtax) @ xtay

    return w


# Testing script
if __name__ == "__main__":
    data1 = linear_data_simulator(prior="Gauss", noise="Gauss")
    data2 = linear_data_simulator(prior="Laplace", noise="Gauss")
    data3 = linear_data_simulator(prior="Gauss", noise="Laplace")
    w1 = omp(data2["train"][0], data2["train"][1], non_zeros=4)
    w2 = training_sgd(data1["train"][0], data1["train"][1], gamma=1)
    w3 = training_lasso(data2["train"][0], data2["train"][1], gamma=1)
    w4 = training_elastic(data2["train"][0], data2["train"][1], gamma1=1, gamma2=1)
    w5 = training_irls(data3["train"][0], data3["train"][1])

    mse_w1 = mse(data2["real"], w1)
    mse_w2 = mse(data1["real"], w2)
    mse_w3 = mse(data2["real"], w3)
    mse_w4 = mse(data2["real"], w4)
    mse_w5 = mse(data3["real"], w5)

    mse_y1 = testing(data2["test"][0], data2["test"][1], w1)
    mse_y2 = testing(data1["test"][0], data1["test"][1], w2)
    mse_y3 = testing(data2["test"][0], data2["test"][1], w3)
    mse_y4 = testing(data2["test"][0], data2["test"][1], w4)
    mse_y5 = testing(data3["test"][0], data3["test"][1], w5)

    print("OMP, mse-w={:.4f}, mse-y={:.4f}".format(mse_w1, mse_y1))
    print("Ridge regression (SGD), mse-w={:.4f}, mse-y={:.4f}".format(mse_w2, mse_y2))
    print("Lasso regularizer, mse-w={:.4f}, mse-y={:.4f}".format(mse_w3, mse_y3))
    print("Elastic Net regularizer, mse-w={:.4f}, mse-y={:.4f}".format(mse_w4, mse_y4))
    print("IRLS, mse-w={:.4f}, mse-y={:.4f}".format(mse_w5, mse_y5))
